### ISSUE TITLE
no exe releases

### ISSUE THREAD

**Issue by mr2meowsYT** [MrMysterio/Uwizard#13]
tf is this i want a release

**Comment by Masamune3210** [comment]
Google is your friend
https://digiex.net/threads/uwizard-wii-u-wud-manager-and-nus-downloader.14679/

Also dont be so needy for free

**Comment by loganboogadooz** [comment]
it wont let me it says The connection was reset

**Comment by SirWrexes** [comment]
You guys really need to hone your Googling skills.
Take your pick :
https://gamebanana.com/tools/6346
https://digiex.net/threads/uwizard-wii-u-wud-manager-and-nus-downloader.14679/
https://gbatemp.net/threads/uwizard-all-in-one-wii-u-pc-program.386508/
https://wiidatabase.de/wii-u-downloads/pc-tools/uwizard/
...

**Comment by ratijas** [comment]
Putting it into more polite form, OP was trying to say that GitHub Releases are more reliable in terms of links lifespan, and more trustworthy because — if anything — they would be moderated by GitHub which some of us may trust more. There just no downsides to using GitHub Releases feature. So, kindly consider using them.

> Also dont be so needy for free

Being free and open source does not have to come with poor service for granted. That's not what the open source is all about.  Please, refrain from such attitude in future.

It is quite natural that there will always be more users than developers/contributors, so it is only to be expected that the majority comes here looking just for binary releases — not for the source code. Their frustration is totally understandable. However, I admit, a better wording could've be chosen.

**Comment by ratijas** [comment]
Besides, here are some binary artifacts in bin/Debug folder. Probably are leftovers from poor git management skills, but whatever. Can't be sure whether they were built from the latest version of code at that time though.

https://github.com/MrMysterio/Uwizard/tree/master/Uwizard/bin/Debug

Just download/clone the whole repo, navigate to _Uwizard/bin/Debug_ directory, and try running required exe from there. Might work.

**Comment by mr2meowsYT** [comment]
i love how lots of issues I made on GitHub years ago are still open
